#!/usr/bin/env zsh

# https://github.com/ThePrimeagen/.dotfiles/blob/master/clean-env

pushd $DOTFILES
for folder in $(echo $STOW_DOTFILES)
do
    echo "Removing $folder"
    stow -D $folder
done
popd
