#!/usr/bin/env zsh

# https://github.com/ThePrimeagen/.dotfiles/blob/master/ubuntu

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

if [[ -z $STOW_DOTFILES ]]; then
    STOW_DOTFILES=$(
        ls -d $DOTFILES/*/ $DOTFILES/.*/ | sed 's/\/$//' | sed -E '/\.git/d' | awk -F \/ '{print $NF}'
    )
fi

STOW_DOTFILES=$STOW_DOTFILES DOTFILES=$DOTFILES $DOTFILES/install
