cabbrev W w
cabbrev Wq wq
cabbrev Wa wa
cabbrev wa1 wa!
cabbrev W1 w!
cabbrev w1 w!
cabbrev wq1 wq!
cabbrev Q q
cabbrev Qa qa
cabbrev Qa1 qa!
cabbrev q1 q!
cabbrev qa1 qa!
cabbrev bd1 bd!
cabbrev hgrep helpgrep
