#!/usr/bin/env bash

# Search git log for regex matches across history
#
# Usage: git-grex <regexp> [git-log-options...]
#
# Examples:
#   git-grex "function.*error"
#   git-grex "Todo:" --since="2024-01-01"
#   git-grex "import.*react" --author="me"

git log --all -G "$1" -p "${@:2}"
