prSections:
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: Involved
  filters: is:open involves:@me -author:@me
  type: null
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues:
    - key: e
      name: edit
      command: >
        nvim --server $NVIM_LISTEN_SOCKET --remote-send "<C-\\><C-n>:tabnew
        | tcd {{.RepoPath}} | Octo issue edit {{.IssueNumber}}<C-m><ESC>"
  prs:
    - key: e
      name: edit
      command: >
        nvim --server $NVIM_LISTEN_SOCKET --remote-send "<C-\\><C-n>:tabnew
        | tcd {{.RepoPath}} | Octo pr edit {{.PrNumber}}<C-m><ESC>"
  branches: []
repoPaths:
  :owner/:repo: ~/Projects/github.com/:owner/:repo
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors:
    background:
      selected: "#510039"
pager:
  diff: less -+F
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
