#!/bin/sh

if git show-ref --verify --quiet refs/heads/master; then
        if ! git show-ref --verify --quiet refs/heads/main; then
                git config remote.upstream.pull master
                git symbolic-ref refs/heads/main refs/heads/master
        fi
fi
