#!/bin/sh

if git show-ref --verify --quiet refs/heads/master; then
        if ! git show-ref --verify --quiet refs/heads/main; then
                git symbolic-ref refs/heads/main refs/heads/master
        fi
        if git show-ref --verify --quiet refs/remotes/upstream/master; then
                git branch --set-upstream-to=upstream/master main
        fi
fi
