vim.cmd.packadd("nvim.undotree")
vim.keymap.set("n", "<leader>u", function()
        local split_width = math.floor(vim.o.columns * 0.27 + 0.5)
        require("undotree").open({ command = split_width .. "vnew" })
end, { desc = "Toggle history window" })
