{
  config,
  lib,
  modulesPath,
  ...
}: let
  inherit (lib) disabled enabled mkDefault;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.loader = {
    systemd-boot = enabled;
    efi.canTouchEfiVariables = true;
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.kernelModules = ["kvm-intel"];

  # fileSystems.* are generated by disko (see disko.nix)
  swapDevices = [];

  # this machine's firmware advertises TPM2 (what?) via ACPI, but no chip in sight, and also delays
  # boot by 90 or sometimes 180 seconds, as devices /dev/{tpm0,tpmrm0} don't respond. NOTE: i'm not
  # sure why i need to disable all of these, but eh, if it works...
  boot.initrd.systemd.tpm2 = disabled;
  systemd.tpm2 = disabled;
  systemd.units."dev-tpm0.device" = disabled;
  systemd.units."dev-tpmrm0.device" = disabled;

  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = mkDefault config.hardware.enableRedistributableFirmware;
}
