"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name  = "yilisharcs"
email = "yilisharcs@gmail.com"

[signing]
behavior = "drop"
backend  = "gpg"
key      = "1D1CA99103BF8677"

[git]
sign-on-push = true

[ui]
default-command = "ls"

[aliases]
amend = ["squash"]
clone = ["git", "clone", "--colocate"]
fetch = ["git", "fetch"]
init  = ["git", "init", "--colocate"]
ls    = ["log", "--summary"]
push  = ["git", "push"]
